source 'https://rubygems.org'
gem 'rails', '4.2.4'
gem 'puma', '~> 2.14.0'
gem 'mysql2', '~> 0.3.19'
gem 'sass-rails', '~> 5.0.4'
gem 'compass-rails', '~> 2.0.5'
gem 'breakpoint', '~> 2.5.0'
gem 'uglifier', '>= 2.7.2'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails', '~> 4.0.5'
gem 'turbolinks', '~> 2.5.3'
gem 'jbuilder', '~> 2.3.1'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'stratosphere', '~> 0.0.2'
gem 'google-analytics-rails', '~> 0.0.6'
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
