development:
  adapter: mysql2
  encoding: utf8
  database: stratosphere-demo
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: stratosphere_demo_test
  username: travis

production:
  adapter: mysql2
  encoding: utf8
  database: stratosphere-demo
  pool: 5
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock